import { useEffect, useState } from "react";
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { youtube, type YouTubeVideo } from "@/lib/youtube";

export default function VideoDetailsScreen(){const {id}=useLocalSearchParams<{id:string}>();const [video,setVideo]=useState<YouTubeVideo|null>(null);const [error,setError]=useState("");useEffect(()=>{if(!id)return;void youtube.fetchVideos().then(items=>setVideo(items.find(item=>item.id===id)??null)).catch(e=>setError(e instanceof Error?e.message:"تعذر تحميل الفيديو حاليًا"))},[id]);return <ScreenContainer edges={["top","bottom","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.icon}><MaterialIcons name="arrow-forward" size={23} color={DESIGN.colors.text}/></Pressable><Text style={styles.headerTitle}>تفاصيل الفيديو</Text><View/></View>{error?<Text style={styles.state}>تعذر تحميل الفيديو حاليًا</Text>:!video?<Text style={styles.state}>جارٍ تحميل بيانات الفيديو…</Text>:<><Image source={{uri:video.thumbnailUrl}} style={styles.image}/><Text style={styles.title}>{video.title}</Text><Text style={styles.date}>{new Date(video.publishedAt).toLocaleDateString("ar-EG")} · {video.duration??"—"}</Text><View style={styles.stats}><Text style={styles.stat}>{video.views??0} مشاهدة</Text><Text style={styles.stat}>Video ID: {video.id}</Text></View><Text style={styles.description}>{video.description||"لا يوجد وصف متاح."}</Text>{video.embeddable?<View style={styles.embed}><MaterialIcons name="play-circle-outline" size={38} color={DESIGN.colors.primary}/><Text style={styles.embedText}>الفيديو قابل للتضمين والتشغيل الرسمي داخل التطبيق.</Text></View>:<View style={styles.embed}><MaterialIcons name="block" size={30} color={DESIGN.colors.danger}/><Text style={styles.embedText}>هذا الفيديو غير قابل للتضمين؛ لن تتم محاولة تجاوز قيود YouTube.</Text></View>}</>}</ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:10,paddingBottom:30},header:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",marginBottom:18},icon:{width:42,height:42,borderRadius:14,backgroundColor:DESIGN.colors.surface,alignItems:"center",justifyContent:"center"},headerTitle:{color:DESIGN.colors.text,fontSize:21,fontWeight:"900"},image:{width:"100%",height:215,borderRadius:20,backgroundColor:DESIGN.colors.surface},title:{color:DESIGN.colors.text,fontSize:21,fontWeight:"900",textAlign:"right",marginTop:18,lineHeight:29},date:{color:DESIGN.colors.primary,textAlign:"right",marginTop:7},stats:{flexDirection:"row-reverse",justifyContent:"space-around",paddingVertical:17,borderTopWidth:1,borderBottomWidth:1,borderColor:DESIGN.colors.border,marginTop:17},stat:{color:DESIGN.colors.textMuted,fontSize:12},description:{color:DESIGN.colors.textMuted,fontSize:14,lineHeight:23,textAlign:"right",marginTop:18},embed:{flexDirection:"row-reverse",alignItems:"center",gap:10,padding:16,borderRadius:16,backgroundColor:DESIGN.colors.surface,marginTop:20},embedText:{color:DESIGN.colors.text,fontSize:13,lineHeight:20,textAlign:"right",flex:1},state:{color:DESIGN.colors.textMuted,textAlign:"center",paddingVertical:50}});
