import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { MOCK_VIDEOS } from "@/constants/mock-data";
import { MockPill } from "@/components/ui/design-components";

export default function VideoDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const video = MOCK_VIDEOS.find((item) => item.id === id) ?? MOCK_VIDEOS[0]; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.icon, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={23} color={DESIGN.colors.text} /></Pressable><Text style={styles.headerTitle}>تفاصيل الفيديو</Text><MockPill /></View><View style={[styles.videoFrame, { backgroundColor: DESIGN.colors.primaryDeep }]}><View style={styles.frameGlow}><MaterialIcons name="biotech" size={60} color="#B9FFF1" /></View><Text style={styles.frameTitle}>{video.title}</Text><Text style={styles.frameSubtitle}>{video.subtitle}</Text><View style={styles.frameDuration}><MaterialIcons name="play-arrow" size={18} color={DESIGN.colors.background} /><Text style={styles.frameDurationText}>{video.duration}</Text></View></View><View style={styles.titleRow}><Text style={styles.detailTitle}>{video.title}</Text><MockPill /></View><Text style={styles.detailSubtitle}>{video.subtitle}</Text><View style={styles.stats}><View><Text style={styles.statValue}>{video.views}</Text><Text style={styles.statLabel}>المشاهدات التجريبية</Text></View><View><Text style={styles.statValue}>{video.published}</Text><Text style={styles.statLabel}>تاريخ النشر</Text></View></View><Text style={styles.description}>هذا المحتوى معروض كبيانات Mock مؤقتة بهدف ضبط تجربة الواجهة. عند ربط YouTube API لاحقًا ستأتي الصورة والعنوان والتاريخ والمعرف من القناة الرسمية.</Text><Pressable onPress={() => {}} style={({ pressed }) => [styles.button, pressed && styles.pressed]}><MaterialIcons name="play-circle-outline" size={20} color={DESIGN.colors.background} /><Text style={styles.buttonText}>مشاهدة عبر YouTube لاحقًا</Text></Pressable></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: DESIGN.colors.surface, alignItems: "center", justifyContent: "center" }, headerTitle: { color: DESIGN.colors.text, fontSize: 21, fontWeight: "900" }, videoFrame: { height: 214, borderRadius: 21, overflow: "hidden", alignItems: "center", justifyContent: "center", position: "relative" }, frameGlow: { width: 100, height: 100, borderRadius: 50, backgroundColor: "#FFFFFF18", alignItems: "center", justifyContent: "center", marginBottom: 12 }, frameTitle: { color: DESIGN.colors.white, fontSize: 25, fontWeight: "900" }, frameSubtitle: { color: "#C4F2EB", fontSize: 14, marginTop: 4 }, frameDuration: { flexDirection: "row-reverse", alignItems: "center", gap: 5, position: "absolute", bottom: 12, left: 12, backgroundColor: DESIGN.colors.accent, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 8 }, frameDurationText: { color: DESIGN.colors.background, fontWeight: "900", fontSize: 12 }, titleRow: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginTop: 21 }, detailTitle: { color: DESIGN.colors.text, fontSize: 21, fontWeight: "900", flex: 1, textAlign: "right" }, detailSubtitle: { color: DESIGN.colors.primary, fontSize: 14, textAlign: "right", marginTop: 5 }, stats: { flexDirection: "row-reverse", justifyContent: "space-around", paddingVertical: 17, marginTop: 17, borderTopWidth: 1, borderBottomWidth: 1, borderColor: DESIGN.colors.border }, statValue: { color: DESIGN.colors.text, fontSize: 13, fontWeight: "800", textAlign: "center" }, statLabel: { color: DESIGN.colors.textMuted, fontSize: 10, marginTop: 4, textAlign: "center" }, description: { color: DESIGN.colors.textMuted, fontSize: 14, lineHeight: 23, textAlign: "right", marginTop: 19 }, button: { backgroundColor: DESIGN.colors.primary, borderRadius: 14, minHeight: 50, marginTop: 20, alignItems: "center", justifyContent: "center", flexDirection: "row-reverse", gap: 7 }, buttonText: { color: DESIGN.colors.background, fontSize: 14, fontWeight: "900" }, pressed: { opacity: 0.62 } });
