import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { ScreenHeader } from "@/components/ui/design-components";

export default function SettingsScreen() { return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="الإعدادات" eyebrow="تفضيلات التطبيق" onBack={() => router.back()} /><View style={styles.card}><MaterialIcons name="tune" size={28} color={DESIGN.colors.primary} /><Text style={styles.title}>تفضيلات المشاهدة</Text><Text style={styles.body}>يمكنك تحديث المحتوى من الشاشات الرئيسية باستخدام السحب للأسفل. إعدادات المصدر الداخلية غير معروضة للمستخدم.</Text></View><View style={styles.footer}><MaterialIcons name="lock-outline" size={17} color={DESIGN.colors.textDim} /><Text style={styles.footerText}>يتم الحفاظ على كود جلب البيانات وتشغيل الفيديو داخل التطبيق.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, card: { alignItems: "center", padding: 28, marginTop: 30, borderRadius: 22, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border }, title: { color: DESIGN.colors.text, fontSize: 19, fontWeight: "900", marginTop: 14 }, body: { color: DESIGN.colors.textMuted, fontSize: 13, lineHeight: 22, textAlign: "center", marginTop: 8 }, footer: { flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 6, marginTop: 24 }, footerText: { color: DESIGN.colors.textDim, fontSize: 11 } });
