import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { OFFICIAL_CHANNEL_HANDLE, OFFICIAL_CHANNEL_ID } from "@/lib/youtube";
import { ScreenHeader } from "@/components/ui/design-components";

export default function SettingsScreen(){return <ScreenContainer edges={["top","bottom","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="إعدادات المصدر" eyebrow="الاتصال الرسمي" onBack={()=>router.back()}/><View style={styles.banner}><MaterialIcons name="verified-user" size={24} color={DESIGN.colors.primary}/><Text style={styles.bannerText}>يتم جلب المحتوى من القناة الرسمية مباشرة. لا تُخزّن بيانات الفيديو داخل التطبيق.</Text></View><View style={styles.sectionHeader}><Text style={styles.sectionTitle}>بيانات القناة المؤكدة</Text></View><Text style={styles.label}>Channel Handle</Text><View style={styles.input}><TextInput value={OFFICIAL_CHANNEL_HANDLE} editable={false} style={styles.inputText} textAlign="left"/></View><Text style={styles.label}>Channel ID</Text><View style={styles.input}><TextInput value={OFFICIAL_CHANNEL_ID} editable={false} style={styles.inputText} textAlign="left"/></View><Text style={styles.note}>مفتاح YouTube Data API v3 محفوظ في إعدادات البيئة الآمنة، ولا يظهر في التطبيق أو السجلات. لا توجد روابط خارجية أو أزرار لفتح YouTube من هذه الشاشة.</Text><View style={styles.footer}><MaterialIcons name="lock-outline" size={17} color={DESIGN.colors.textDim}/><Text style={styles.footerText}>لا توجد قاعدة بيانات أو Backend أو تخزين فيديوهات</Text></View></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:10,paddingBottom:30},banner:{flexDirection:"row-reverse",alignItems:"center",gap:10,padding:16,borderRadius:18,backgroundColor:DESIGN.colors.primarySoft,borderWidth:1,borderColor:DESIGN.colors.border},bannerText:{flex:1,color:DESIGN.colors.text,fontSize:13,lineHeight:21,textAlign:"right"},sectionHeader:{flexDirection:"row-reverse",justifyContent:"flex-start",alignItems:"center",marginTop:25,marginBottom:8},sectionTitle:{color:DESIGN.colors.text,fontSize:18,fontWeight:"900"},label:{color:DESIGN.colors.textMuted,fontSize:13,fontWeight:"700",textAlign:"right",marginTop:12,marginBottom:7},input:{height:52,borderRadius:15,borderWidth:1,borderColor:DESIGN.colors.border,backgroundColor:DESIGN.colors.surface,justifyContent:"center",paddingHorizontal:14},inputText:{color:DESIGN.colors.text,fontSize:14},note:{color:DESIGN.colors.textMuted,fontSize:13,lineHeight:22,textAlign:"right",marginTop:17},footer:{flexDirection:"row-reverse",justifyContent:"center",alignItems:"center",gap:6,marginTop:24},footerText:{color:DESIGN.colors.textDim,fontSize:11}});
