import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { ScreenHeader } from "@/components/ui/design-components";
import { useAuth } from "@/hooks/use-auth";

export default function SettingsScreen() {
  const { user, loading, logout } = useAuth();
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="الإعدادات" eyebrow="تفضيلات التطبيق" onBack={() => router.back()} />
    <View style={styles.accountCard}><MaterialIcons name="account-circle" size={34} color={DESIGN.colors.primary} /><Text style={styles.title}>الحساب</Text>{loading ? <ActivityIndicator color={DESIGN.colors.primary} /> : user ? <><Text style={styles.accountName}>{user.name || "حساب Google"}</Text><Text style={styles.accountEmail}>{user.email || "تم تسجيل الدخول"}</Text><Text style={styles.accountStatus}>مسجل الدخول عبر Google</Text><Pressable onPress={() => void logout()} style={({ pressed }) => [styles.logoutButton, pressed && styles.pressed]}><MaterialIcons name="logout" size={19} color={DESIGN.colors.danger} /><Text style={styles.logoutText}>تسجيل الخروج</Text></Pressable></> : <Text style={styles.body}>لا يوجد حساب مسجل حاليًا.</Text>}</View>
    <View style={styles.card}><MaterialIcons name="tune" size={28} color={DESIGN.colors.primary} /><Text style={styles.title}>تفضيلات المشاهدة</Text><Text style={styles.body}>يمكنك تحديث المحتوى من الشاشات الرئيسية باستخدام السحب للأسفل. إعدادات المصدر الداخلية غير معروضة للمستخدم.</Text></View><View style={styles.footer}><MaterialIcons name="lock-outline" size={17} color={DESIGN.colors.textDim} /><Text style={styles.footerText}>يتم الحفاظ على كود جلب البيانات وتشغيل الفيديو داخل التطبيق.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, accountCard: { alignItems: "center", padding: 22, marginTop: 22, borderRadius: 22, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border }, accountName: { color: DESIGN.colors.text, fontSize: 18, fontWeight: "900", marginTop: 10 }, accountEmail: { color: DESIGN.colors.textMuted, fontSize: 13, marginTop: 4 }, accountStatus: { color: DESIGN.colors.primary, fontSize: 12, marginTop: 7 }, logoutButton: { flexDirection: "row-reverse", alignItems: "center", gap: 7, paddingHorizontal: 15, paddingVertical: 10, borderRadius: 12, backgroundColor: "#3a1e24", marginTop: 16 }, logoutText: { color: DESIGN.colors.danger, fontWeight: "900" }, pressed: { opacity: 0.75 }, card: { alignItems: "center", padding: 28, marginTop: 18, borderRadius: 22, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border }, title: { color: DESIGN.colors.text, fontSize: 19, fontWeight: "900", marginTop: 14 }, body: { color: DESIGN.colors.textMuted, fontSize: 13, lineHeight: 22, textAlign: "center", marginTop: 8 }, footer: { flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 6, marginTop: 24 }, footerText: { color: DESIGN.colors.textDim, fontSize: 11 } });
