import { ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { EmptyState, ScreenHeader } from "@/components/ui/design-components";

export default function DownloadsScreen() { return <ScreenContainer edges={["top", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="التنزيلات" eyebrow="دروسك في متناولك" onSearch={() => router.push("/(tabs)/search")} onNotifications={() => {}} /><View style={styles.storage}><View style={styles.storageIcon}><MaterialIcons name="download-for-offline" size={24} color={DESIGN.colors.primary} /></View><View style={styles.storageCopy}><Text style={styles.storageTitle}>المشاهدة دون اتصال</Text><Text style={styles.storageText}>واجهة جاهزة لإضافة الميزة لاحقًا وفق سياسات YouTube.</Text></View><Text style={styles.storageValue}>—</Text></View><EmptyState icon="download-for-offline" title="لا توجد تنزيلات" body="لن يتم تنزيل أو استضافة أي فيديو في هذه المرحلة. هذه الشاشة جزء من نظام التصميم فقط." action="استكشاف الفيديوهات" onPress={() => router.push("/(tabs)/videos")} /><View style={styles.note}><MaterialIcons name="info-outline" size={18} color={DESIGN.colors.textMuted} /><Text style={styles.noteText}>سيتم تحديد دعم التنزيلات لاحقًا بما يتوافق مع الطريقة الرسمية المسموح بها.</Text></View></ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 25 }, storage: { flexDirection: "row-reverse", alignItems: "center", gap: 12, backgroundColor: DESIGN.colors.surface, borderRadius: 18, borderWidth: 1, borderColor: DESIGN.colors.border, padding: 14, marginBottom: 20 }, storageIcon: { width: 45, height: 45, borderRadius: 14, backgroundColor: DESIGN.colors.primarySoft, alignItems: "center", justifyContent: "center" }, storageCopy: { flex: 1, alignItems: "flex-end" }, storageTitle: { color: DESIGN.colors.text, fontWeight: "800", fontSize: 15 }, storageText: { color: DESIGN.colors.textMuted, fontSize: 11, marginTop: 4, textAlign: "right" }, storageValue: { color: DESIGN.colors.textDim, fontSize: 18 }, note: { flexDirection: "row-reverse", alignItems: "center", gap: 7, marginTop: 18, paddingHorizontal: 12 }, noteText: { flex: 1, color: DESIGN.colors.textDim, fontSize: 11, lineHeight: 18, textAlign: "right" } });
