import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { MOCK_PLAYLISTS, MOCK_VIDEOS } from "@/constants/mock-data";
import { PlaylistCard, SectionHeading, VideoCard } from "@/components/ui/design-components";
import { OFFICIAL_CHANNEL_HANDLE, OFFICIAL_CHANNEL_URL } from "@/lib/youtube";
import * as Linking from "expo-linking";

const shortcuts = [
  { label: "المنهج", icon: "menu-book" as const, color: DESIGN.colors.primary },
  { label: "قوائم التشغيل", icon: "format-list-bulleted" as const, color: "#9C74D9" },
  { label: "المفضلة", icon: "favorite-border" as const, color: "#E58B9C" },
  { label: "المحفوظات", icon: "schedule" as const, color: "#E0B858" },
  { label: "الملاحظات", icon: "bookmark-border" as const, color: "#C37DE1" },
];

export default function HomeScreen() {
  return <ScreenContainer edges={["top", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <View style={styles.topBar}><View style={styles.actions}><Pressable accessibilityLabel="الإشعارات" onPress={() => Alert.alert("الإشعارات", "لا توجد إشعارات جديدة في العرض التجريبي.")} style={({ pressed }) => [styles.topIcon, pressed && styles.pressed]}><MaterialIcons name="notifications-none" size={25} color={DESIGN.colors.text} /></Pressable><Pressable accessibilityLabel="البحث" onPress={() => router.push("/(tabs)/search")} style={({ pressed }) => [styles.topIcon, pressed && styles.pressed]}><MaterialIcons name="search" size={27} color={DESIGN.colors.text} /></Pressable></View><View style={styles.greeting}><Text style={styles.hello}>مرحبًا بك</Text><Text style={styles.appTitle}>أحياء مع الباز</Text></View></View>
    <View style={styles.hero}><View style={styles.heroTop}><View style={styles.avatarRing}><Image source={require("@/assets/images/professor-avatar.png")} style={styles.avatar} /><View style={styles.avatarAccent} /></View><View style={styles.heroIdentity}><Text style={styles.heroName}>الأستاذ عبدالرحمن الباز</Text><Text style={styles.heroHandle}>{OFFICIAL_CHANNEL_HANDLE}</Text></View></View><Text style={styles.heroCopy}>رحلتك في الأحياء تبدأ من هنا <Text style={styles.leaf}>◒</Text></Text><Text style={styles.heroSub}>شرح مبسط · فهم عميق · نجاح بإذن الله</Text><Pressable onPress={() => Linking.openURL(OFFICIAL_CHANNEL_URL)} style={({ pressed }) => [styles.heroButton, pressed && styles.pressed]}><Text style={styles.heroButtonText}>زيارة القناة الرسمية</Text><MaterialIcons name="arrow-back" size={17} color={DESIGN.colors.background} /></Pressable></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.shortcuts}>{shortcuts.map((item) => <Pressable key={item.label} onPress={() => router.push("/(tabs)/videos")} style={({ pressed }) => [styles.shortcut, pressed && styles.pressed]}><View style={[styles.shortcutIcon, { backgroundColor: `${item.color}24` }]}><MaterialIcons name={item.icon} size={24} color={item.color} /></View><Text style={styles.shortcutLabel}>{item.label}</Text></Pressable>)}</ScrollView>
    <SectionHeading title="أحدث الفيديوهات" onAction={() => router.push("/(tabs)/videos")} />
    {MOCK_VIDEOS.map((video) => <VideoCard key={video.id} video={video} />)}
    <SectionHeading title="قوائم التشغيل" onAction={() => router.push("/(tabs)/playlists")} />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.playlists}>{MOCK_PLAYLISTS.map((playlist) => <PlaylistCard key={playlist.id} playlist={playlist} />)}</ScrollView>
    <View style={styles.mockNotice}><MaterialIcons name="science" size={16} color={DESIGN.colors.accent} /><Text style={styles.mockNoticeText}>المحتوى الظاهر حاليًا تجريبي لتصميم الواجهة فقط</Text></View>
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 30 }, topBar: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, actions: { flexDirection: "row", gap: 9 }, topIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: DESIGN.colors.surface, alignItems: "center", justifyContent: "center" }, greeting: { alignItems: "flex-end" }, hello: { color: DESIGN.colors.textMuted, fontSize: 13, marginBottom: 2 }, appTitle: { color: DESIGN.colors.text, fontSize: 23, fontWeight: "900" }, hero: { borderRadius: 25, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border, padding: 18, marginBottom: 15, overflow: "hidden" }, heroTop: { flexDirection: "row-reverse", alignItems: "center", gap: 12 }, avatarRing: { width: 76, height: 76, borderRadius: 38, backgroundColor: DESIGN.colors.primaryDeep, alignItems: "center", justifyContent: "center", position: "relative" }, avatar: { width: 65, height: 65, borderRadius: 33 }, avatarAccent: { position: "absolute", width: 86, height: 86, borderRadius: 43, borderWidth: 1, borderColor: `${DESIGN.colors.primary}60` }, heroIdentity: { flex: 1, alignItems: "flex-end" }, heroName: { color: DESIGN.colors.text, fontSize: 18, fontWeight: "900", textAlign: "right" }, heroHandle: { color: DESIGN.colors.primary, fontSize: 13, marginTop: 4 }, heroCopy: { color: DESIGN.colors.text, fontSize: 20, fontWeight: "900", textAlign: "right", marginTop: 17 }, leaf: { color: DESIGN.colors.primary, fontSize: 23 }, heroSub: { color: DESIGN.colors.textMuted, fontSize: 13, textAlign: "right", marginTop: 5 }, heroButton: { marginTop: 16, backgroundColor: DESIGN.colors.primary, borderRadius: 13, minHeight: 43, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 7 }, heroButtonText: { color: DESIGN.colors.background, fontWeight: "900", fontSize: 14 }, shortcuts: { gap: 7, paddingBottom: 5, paddingHorizontal: 1, flexDirection: "row-reverse" }, shortcut: { backgroundColor: DESIGN.colors.surface, borderRadius: 17, width: 66, height: 92, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: DESIGN.colors.border, gap: 7 }, shortcutIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, shortcutLabel: { color: DESIGN.colors.text, fontSize: 11, fontWeight: "700", textAlign: "center" }, playlists: { paddingBottom: 4, paddingLeft: 2, flexDirection: "row-reverse" }, mockNotice: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 5, marginTop: 20 }, mockNoticeText: { color: DESIGN.colors.textDim, fontSize: 11 }, pressed: { opacity: 0.62 }, });
