import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { OFFICIAL_CHANNEL_ID } from "@/lib/youtube";
import { ScreenHeader } from "@/components/ui/design-components";

const items = [{label:"إعدادات مصدر YouTube",icon:"tune" as const,route:"settings"},{label:"حالة الاتصال",icon:"cloud-done" as const,route:"status"},{label:"عن التطبيق",icon:"info-outline" as const,route:"about"}];
export default function MoreScreen(){return <ScreenContainer edges={["top","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenHeader title="المزيد" eyebrow="مساحتك التعليمية" onSearch={()=>router.push("/(tabs)/search")} onNotifications={()=>{}}/><View style={styles.profile}><View style={styles.profileAvatar}><Text style={styles.profileAvatarText}>ع</Text></View><View style={styles.profileCopy}><Text style={styles.profileTitle}>أحياء مع عبدالرحمن الباز</Text><Text style={styles.profileText}>محتوى القناة الرسمية داخل التطبيق</Text></View></View><Text style={styles.heading}>التفضيلات والمعلومات</Text>{items.map(item=><Pressable key={item.label} onPress={()=>item.route==="settings"?router.push("/settings"):item.route==="status"?Alert.alert("حالة الاتصال",`المصدر الرسمي مضبوط على Channel ID: ${OFFICIAL_CHANNEL_ID}`):Alert.alert("عن التطبيق","واجهة تعليمية لمحتوى الأستاذ عبدالرحمن الباز. يتم جلب البيانات الحقيقية مباشرة من YouTube.")} style={styles.row}><View style={styles.chevron}><MaterialIcons name="chevron-left" size={21} color={DESIGN.colors.textMuted}/></View><Text style={styles.rowLabel}>{item.label}</Text><View style={styles.rowIcon}><MaterialIcons name={item.icon} size={21} color={DESIGN.colors.primary}/></View></Pressable>)}<View style={styles.brand}><Text style={styles.brandTitle}>مصمم لرحلة فهم الأحياء</Text><Text style={styles.brandText}>لا توجد روابط خارجية أو تنزيلات أو تخزين للفيديوهات.</Text></View></ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:10,paddingBottom:25},profile:{flexDirection:"row-reverse",alignItems:"center",gap:12,padding:16,borderRadius:19,backgroundColor:DESIGN.colors.surface,borderWidth:1,borderColor:DESIGN.colors.border},profileAvatar:{width:49,height:49,borderRadius:17,backgroundColor:DESIGN.colors.primaryDeep,alignItems:"center",justifyContent:"center"},profileAvatarText:{color:DESIGN.colors.white,fontSize:23,fontWeight:"900"},profileCopy:{flex:1,alignItems:"flex-end"},profileTitle:{color:DESIGN.colors.text,fontSize:14,fontWeight:"800",textAlign:"right"},profileText:{color:DESIGN.colors.textMuted,fontSize:11,marginTop:4,textAlign:"right"},heading:{color:DESIGN.colors.text,fontSize:18,fontWeight:"900",textAlign:"right",marginTop:25,marginBottom:10},row:{minHeight:59,borderRadius:16,backgroundColor:DESIGN.colors.surface,borderWidth:1,borderColor:DESIGN.colors.border,flexDirection:"row-reverse",alignItems:"center",paddingHorizontal:14,gap:12,marginBottom:9},rowIcon:{width:35,height:35,borderRadius:12,backgroundColor:DESIGN.colors.primarySoft,alignItems:"center",justifyContent:"center"},rowLabel:{flex:1,color:DESIGN.colors.text,fontSize:14,fontWeight:"700",textAlign:"right"},chevron:{width:24,alignItems:"center"},brand:{alignItems:"center",marginTop:28,padding:18},brandTitle:{color:DESIGN.colors.primary,fontSize:14,fontWeight:"800"},brandText:{color:DESIGN.colors.textDim,fontSize:11,textAlign:"center",marginTop:6}});
