import { useCallback, useEffect, useState } from "react";
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { youtube, type YouTubePlaylist } from "@/lib/youtube";

export default function PlaylistsScreen() { const [items,setItems]=useState<YouTubePlaylist[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const load=useCallback(async(r=false)=>{if(r)setRefreshing(true);else setLoading(true);setError("");try{setItems(await youtube.fetchPlaylists())}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل قوائم التشغيل حاليًا")}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);return <ScreenContainer edges={["top","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={DESIGN.colors.primary}/>} contentContainerStyle={styles.content}><Text style={styles.title}>قوائم التشغيل</Text><Text style={styles.eyebrow}>المسارات الحقيقية من القناة الرسمية</Text>{loading?<Text style={styles.state}>جارٍ تحميل قوائم التشغيل…</Text>:error?<Text style={styles.state}>تعذر تحميل قوائم التشغيل حاليًا</Text>:items.length===0?<Text style={styles.state}>لا توجد قوائم تشغيل عامة متاحة.</Text>:<View style={styles.grid}>{items.map(item=><Pressable key={item.id} onPress={()=>router.push({pathname:"/playlist/[id]",params:{id:item.id}})} style={styles.card}>{item.thumbnailUrl?<Image source={{uri:item.thumbnailUrl}} style={StyleSheet.absoluteFill}/>:null}<View style={styles.overlay}/><View style={styles.copy}><Text numberOfLines={2} style={styles.cardTitle}>{item.title}</Text><Text style={styles.count}>{item.itemCount??"—"} فيديو</Text></View></Pressable>)}</View>}</ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:12,paddingBottom:30},title:{color:DESIGN.colors.text,fontSize:26,fontWeight:"900",textAlign:"right"},eyebrow:{color:DESIGN.colors.primary,fontSize:12,textAlign:"right",marginTop:4,marginBottom:18},grid:{flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:10},card:{width:"48%",height:170,borderRadius:18,overflow:"hidden",padding:14,justifyContent:"flex-end",position:"relative",backgroundColor:DESIGN.colors.surface},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:"#073b3baa"},copy:{zIndex:2,alignItems:"flex-end"},cardTitle:{color:DESIGN.colors.white,fontSize:16,fontWeight:"900",textAlign:"right"},count:{color:"#D0EFEB",fontSize:12,marginTop:5},state:{color:DESIGN.colors.textMuted,textAlign:"center",paddingVertical:50}});
