import { useMemo, useState } from "react";
import { ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { MOCK_VIDEOS } from "@/constants/mock-data";
import { MockPill, ScreenHeader, VideoCard } from "@/components/ui/design-components";

export default function SearchTabScreen() { const [query, setQuery] = useState(""); const results = useMemo(() => MOCK_VIDEOS.filter((v) => `${v.title} ${v.subtitle}`.includes(query.trim())), [query]); return <ScreenContainer edges={["top", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><ScreenHeader title="البحث" eyebrow="اكتشف دروسك" onNotifications={() => {}} /><View style={styles.searchBox}><MaterialIcons name="search" size={22} color={DESIGN.colors.primary} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث عن درس أو موضوع" placeholderTextColor={DESIGN.colors.textDim} style={styles.input} textAlign="right" /></View><View style={styles.resultHeader}><MockPill /><Text style={styles.resultTitle}>{query ? `${results.length} نتائج تجريبية` : "اقتراحات البحث"}</Text></View>{results.length ? results.map((video) => <VideoCard key={video.id} video={video} />) : <View style={styles.empty}><MaterialIcons name="search-off" size={31} color={DESIGN.colors.primary} /><Text style={styles.emptyTitle}>لا توجد نتائج</Text><Text style={styles.emptyText}>جرّب كلمة مختلفة للبحث داخل المحتوى التجريبي.</Text></View>}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 25 }, searchBox: { height: 54, borderRadius: 17, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border, flexDirection: "row-reverse", alignItems: "center", gap: 9, paddingHorizontal: 14 }, input: { flex: 1, color: DESIGN.colors.text, fontSize: 15 }, resultHeader: { flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center", marginTop: 23, marginBottom: 12 }, resultTitle: { color: DESIGN.colors.text, fontSize: 18, fontWeight: "900" }, empty: { borderRadius: 20, backgroundColor: DESIGN.colors.surface, paddingVertical: 45, alignItems: "center", gap: 9 }, emptyTitle: { color: DESIGN.colors.text, fontSize: 17, fontWeight: "800" }, emptyText: { color: DESIGN.colors.textMuted, fontSize: 13 } });
