import { useCallback, useEffect, useMemo, useState } from "react";
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { youtube, type YouTubeVideo } from "@/lib/youtube";

export default function SearchTabScreen() {
  const [query, setQuery] = useState("");
  const [videos, setVideos] = useState<YouTubeVideo[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async (refresh = false) => { if (refresh) setRefreshing(true); else setLoading(true); setError(""); try { setVideos(await youtube.fetchVideos()); } catch (cause) { setError(cause instanceof Error ? cause.message : "تعذر تحميل فيديوهات القناة حاليًا"); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const results = useMemo(() => { const normalized = query.trim().toLocaleLowerCase("ar"); return normalized ? videos.filter(video => video.title.toLocaleLowerCase("ar").includes(normalized) || video.description.toLocaleLowerCase("ar").includes(normalized)) : videos; }, [videos, query]);
  return <ScreenContainer edges={["top", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView showsVerticalScrollIndicator={false} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={DESIGN.colors.primary} />} contentContainerStyle={styles.content}><Text style={styles.title}>البحث</Text><Text style={styles.eyebrow}>ابحث داخل فيديوهات القناة الحقيقية</Text><View style={styles.searchBox}><MaterialIcons name="search" size={22} color={DESIGN.colors.primary} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث عن درس أو موضوع" placeholderTextColor={DESIGN.colors.textDim} style={styles.input} textAlign="right" /></View>{loading ? <State title="جارٍ تحميل الفيديوهات" body="يتم البحث داخل المحتوى الحقيقي للقناة." /> : error ? <State title="تعذر تحميل نتائج البحث" body={error} action="إعادة المحاولة" onPress={() => void load()} /> : results.length ? <>{query ? <Text style={styles.resultTitle}>{results.length} نتيجة حقيقية</Text> : null}{results.map(video => <Pressable key={video.id} onPress={() => router.push({ pathname: "/video/[id]", params: { id: video.id } })} style={styles.card}><Image source={{ uri: video.thumbnailUrl }} style={styles.thumb} /><View style={styles.meta}><Text numberOfLines={3} style={styles.cardTitle}>{video.title}</Text><Text style={styles.sub}>{new Date(video.publishedAt).toLocaleDateString("ar-EG")} · {video.views ?? 0} مشاهدة</Text></View></Pressable>)}</> : <State title="لا توجد نتائج" body={query ? "جرّب كلمة مختلفة داخل محتوى القناة الحقيقي." : "لا توجد فيديوهات عامة متاحة حاليًا."} />}</ScrollView></ScreenContainer>;
}
function State({ title, body, action, onPress }: { title: string; body: string; action?: string; onPress?: () => void }) { return <View style={styles.state}><MaterialIcons name="info-outline" size={31} color={DESIGN.colors.primary} /><Text style={styles.stateTitle}>{title}</Text><Text style={styles.stateBody}>{body}</Text>{action && onPress ? <Pressable onPress={onPress} style={styles.button}><Text style={styles.buttonText}>{action}</Text></Pressable> : null}</View>; }
const styles = StyleSheet.create({ content: { paddingTop: 12, paddingBottom: 30 }, title: { color: DESIGN.colors.text, fontSize: 27, fontWeight: "900", textAlign: "right" }, eyebrow: { color: DESIGN.colors.primary, fontSize: 12, textAlign: "right", marginTop: 4, marginBottom: 18 }, searchBox: { flexDirection: "row-reverse", alignItems: "center", gap: 9, borderRadius: 15, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border, paddingHorizontal: 13, marginBottom: 17 }, input: { flex: 1, color: DESIGN.colors.text, paddingVertical: 13, fontSize: 14 }, resultTitle: { color: DESIGN.colors.textMuted, textAlign: "right", fontSize: 13, marginBottom: 10 }, card: { flexDirection: "row", gap: 12, padding: 9, borderRadius: 18, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border, marginBottom: 11 }, thumb: { width: 146, height: 92, borderRadius: 13, backgroundColor: DESIGN.colors.border }, meta: { flex: 1, alignItems: "flex-end", justifyContent: "center" }, cardTitle: { color: DESIGN.colors.text, fontSize: 15, fontWeight: "800", lineHeight: 20, textAlign: "right" }, sub: { color: DESIGN.colors.textMuted, fontSize: 11, marginTop: 8 }, state: { paddingVertical: 42, paddingHorizontal: 24, alignItems: "center", borderRadius: 20, backgroundColor: DESIGN.colors.surface, borderWidth: 1, borderColor: DESIGN.colors.border }, stateTitle: { color: DESIGN.colors.text, fontSize: 17, fontWeight: "800", textAlign: "center", marginTop: 12 }, stateBody: { color: DESIGN.colors.textMuted, fontSize: 13, lineHeight: 21, textAlign: "center", marginTop: 6 }, button: { backgroundColor: DESIGN.colors.primary, borderRadius: 12, paddingVertical: 11, paddingHorizontal: 18, marginTop: 15 }, buttonText: { color: DESIGN.colors.background, fontWeight: "900" } });
