import { useCallback, useEffect, useMemo, useState } from "react";
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { router } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { youtube, type YouTubeVideo } from "@/lib/youtube";

export default function VideosScreen() { const [videos,setVideos]=useState<YouTubeVideo[]>([]); const [q,setQ]=useState(""); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState(""); const load=useCallback(async(r=false)=>{r?setRefreshing(true):setLoading(true);setError("");try{setVideos(await youtube.fetchVideos())}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل محتوى القناة حاليًا")}finally{setLoading(false);setRefreshing(false)}},[]);useEffect(()=>{void load()},[load]);const filtered=useMemo(()=>videos.filter(v=>v.title.toLowerCase().includes(q.toLowerCase())),[videos,q]);return <ScreenContainer edges={["top","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={DESIGN.colors.primary}/>} contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.title}>الفيديوهات</Text><Text style={styles.eyebrow}>المحتوى الحقيقي من القناة الرسمية</Text></View><TextInput value={q} onChangeText={setQ} placeholder="ابحث في الفيديوهات" placeholderTextColor={DESIGN.colors.textMuted} style={styles.input}/>{loading?<Text style={styles.state}>جارٍ تحميل الفيديوهات…</Text>:error?<Text style={styles.state}>تعذر تحميل محتوى القناة حاليًا</Text>:filtered.length===0?<Text style={styles.state}>لا توجد نتائج مطابقة.</Text>:filtered.map(v=><Pressable key={v.id} onPress={()=>router.push({pathname:"/video/[id]",params:{id:v.id}})} style={styles.card}><Image source={{uri:v.thumbnailUrl}} style={styles.thumb}/><View style={styles.meta}><Text numberOfLines={3} style={styles.videoTitle}>{v.title}</Text><Text style={styles.sub}>{new Date(v.publishedAt).toLocaleDateString("ar-EG")} · {v.views??0} مشاهدة</Text></View></Pressable>)}</ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:12,paddingBottom:30},header:{alignItems:"flex-end",marginBottom:16},title:{color:DESIGN.colors.text,fontSize:26,fontWeight:"900"},eyebrow:{color:DESIGN.colors.primary,fontSize:12,marginTop:4},input:{backgroundColor:DESIGN.colors.surface,borderColor:DESIGN.colors.border,borderWidth:1,borderRadius:14,color:DESIGN.colors.text,textAlign:"right",padding:13,marginBottom:16},card:{flexDirection:"row",gap:12,padding:9,borderRadius:18,backgroundColor:DESIGN.colors.surface,borderWidth:1,borderColor:DESIGN.colors.border,marginBottom:11},thumb:{width:146,height:92,borderRadius:13,backgroundColor:DESIGN.colors.border},meta:{flex:1,alignItems:"flex-end",justifyContent:"center"},videoTitle:{color:DESIGN.colors.text,fontSize:15,fontWeight:"800",lineHeight:20,textAlign:"right"},sub:{color:DESIGN.colors.textMuted,fontSize:11,marginTop:8},state:{color:DESIGN.colors.textMuted,textAlign:"center",paddingVertical:50}});
