import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { MOCK_PLAYLISTS, MOCK_VIDEOS } from "@/constants/mock-data";
import { MockPill, VideoCard } from "@/components/ui/design-components";

export default function PlaylistDetailsScreen() { const { id } = useLocalSearchParams<{ id: string }>(); const playlist = MOCK_PLAYLISTS.find((item) => item.id === id) ?? MOCK_PLAYLISTS[0]; return <ScreenContainer edges={["top", "bottom", "left", "right"]} className="px-4" containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.icon, pressed && styles.pressed]}><MaterialIcons name="arrow-forward" size={23} color={DESIGN.colors.text} /></Pressable><Text style={styles.headerTitle}>قائمة التشغيل</Text><MockPill /></View><View style={styles.hero}><View style={styles.heroArt}><Text style={styles.heroArtText}>{playlist.icon}</Text></View><View style={styles.heroCopy}><Text style={styles.heroTitle}>{playlist.title}</Text><Text style={styles.heroCount}>{playlist.count} · محتوى تجريبي</Text></View></View><Text style={styles.sectionTitle}>دروس القائمة</Text>{MOCK_VIDEOS.map((video) => <VideoCard key={video.id} video={video} />)}</ScrollView></ScreenContainer>; }
const styles = StyleSheet.create({ content: { paddingTop: 10, paddingBottom: 25 }, header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 18 }, icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: DESIGN.colors.surface, alignItems: "center", justifyContent: "center" }, headerTitle: { color: DESIGN.colors.text, fontSize: 21, fontWeight: "900" }, hero: { borderRadius: 21, backgroundColor: DESIGN.colors.primarySoft, padding: 18, flexDirection: "row-reverse", alignItems: "center", gap: 14, marginBottom: 22 }, heroArt: { width: 78, height: 78, borderRadius: 24, backgroundColor: "#FFFFFF1D", alignItems: "center", justifyContent: "center" }, heroArtText: { color: "#B9FFF1", fontSize: 47 }, heroCopy: { flex: 1, alignItems: "flex-end" }, heroTitle: { color: DESIGN.colors.text, fontSize: 21, fontWeight: "900", textAlign: "right" }, heroCount: { color: DESIGN.colors.textMuted, fontSize: 13, marginTop: 5 }, sectionTitle: { color: DESIGN.colors.text, fontSize: 19, fontWeight: "900", textAlign: "right", marginBottom: 12 }, pressed: { opacity: 0.62 } });
