import { useCallback, useEffect, useState } from "react";
import { Image, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { MaterialIcons } from "@expo/vector-icons";
import { ScreenContainer } from "@/components/screen-container";
import { DESIGN } from "@/constants/design-system";
import { youtube, type YouTubePlaylistItem } from "@/lib/youtube";

export default function PlaylistDetailsScreen(){const {id}=useLocalSearchParams<{id:string}>();const [items,setItems]=useState<YouTubePlaylistItem[]>([]);const [loading,setLoading]=useState(true);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState("");const load=useCallback(async(r=false)=>{if(!id)return;if(r)setRefreshing(true);else setLoading(true);setError("");try{setItems(await youtube.fetchPlaylistItems(id))}catch(e){setError(e instanceof Error?e.message:"تعذر تحميل عناصر القائمة حاليًا")}finally{setLoading(false);setRefreshing(false)}},[id]);useEffect(()=>{void load()},[load]);return <ScreenContainer edges={["top","bottom","left","right"]} className="px-4" containerClassName="bg-background"><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={DESIGN.colors.primary}/>} contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={()=>router.back()} style={styles.icon}><MaterialIcons name="arrow-forward" size={23} color={DESIGN.colors.text}/></Pressable><Text style={styles.headerTitle}>قائمة التشغيل</Text><View/></View>{loading?<Text style={styles.state}>جارٍ تحميل عناصر القائمة…</Text>:error?<Text style={styles.state}>تعذر تحميل عناصر القائمة حاليًا</Text>:items.length===0?<Text style={styles.state}>لا توجد فيديوهات عامة في هذه القائمة.</Text>:items.map((item,index)=><Pressable key={item.id} onPress={()=>router.push({pathname:"/video/[id]",params:{id:item.videoId}})} style={styles.row}><Text style={styles.position}>{index+1}</Text><Image source={{uri:item.thumbnailUrl}} style={styles.thumb}/><View style={styles.copy}><Text numberOfLines={2} style={styles.itemTitle}>{item.title}</Text><Text style={styles.sub}>{new Date(item.publishedAt).toLocaleDateString("ar-EG")}</Text></View></Pressable>)}</ScrollView></ScreenContainer>}
const styles=StyleSheet.create({content:{paddingTop:10,paddingBottom:25},header:{flexDirection:"row-reverse",alignItems:"center",justifyContent:"space-between",marginBottom:18},icon:{width:42,height:42,borderRadius:14,backgroundColor:DESIGN.colors.surface,alignItems:"center",justifyContent:"center"},headerTitle:{color:DESIGN.colors.text,fontSize:21,fontWeight:"900"},row:{flexDirection:"row-reverse",alignItems:"center",gap:10,padding:9,borderRadius:16,backgroundColor:DESIGN.colors.surface,borderWidth:1,borderColor:DESIGN.colors.border,marginBottom:10},position:{color:DESIGN.colors.primary,fontSize:15,fontWeight:"900",width:22,textAlign:"center"},thumb:{width:120,height:76,borderRadius:11},copy:{flex:1,alignItems:"flex-end"},itemTitle:{color:DESIGN.colors.text,fontSize:14,fontWeight:"800",textAlign:"right"},sub:{color:DESIGN.colors.textMuted,fontSize:11,marginTop:6},state:{color:DESIGN.colors.textMuted,textAlign:"center",paddingVertical:50}});
